// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Resolve one explicitly invoked command from this thread's live skill catalog.
 */
export type ClaudeCommandExpandParams = { threadId: string, cwd: string, name: string, path: AbsolutePathBuf, arguments: string, };
