// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Claude Markdown invocation metadata. An absent value keeps older catalogs compatible.
 */
export type ClaudeCommandMetadata = { userInvocable: boolean, argumentHint: string | null, };
