// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Queue a native workflow on an existing thread, preserving that thread's authority.
 */
export type WorkflowStartParams = { threadId: string, scriptPath: string, args: JsonValue, runId: string, };
