// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acceptance is not completion. Observe the native workflow and child events.
 */
export type WorkflowStartResponse = { runId: string, submissionId: string, };
